### ISSUE TITLE
Final TODO 

### ISSUE THREAD

**Issue by straker** [straker/js13k-2021#30]
- [x] Building menubar tooltips
- [x] Delete action
- [x] Miners
  - [x] Copper Miner
  - [x] Iron Miner
  - [x] Titanium Miner
  - [x] Hydrogen Miner
  - [x] Oxygen Miner
- [x] ~~Chemical plant (hydrogen -> fuel, hydrogen + oxygen -> water)~~
- [x] Recipes / Components (icons)
  - [x] Iron
  - [x] Titanium
  - [x] Hydrogen
  - [x] Oxygen
  - [x] Copper Wire (1 copper -> 1 wire)
  - [x] Circuit (2 wire + 1 iron -> 1 circuit)
  - [x] Fuel (? hydrogen -> 1 fuel)
  - [x] Water (1 hydrogen + 2 oxygen -> 1 water)
  - [x] ~~Impulse Drive System (? fuel + ? circuit + ? titanium -> 1 impulse drive system)~~
  - [x] ~~Environmental System (? water + ? oxygen + ? circuit + ? titanium -> 1 environmental system)~~
- [x] Building costs
  - [x] Belt (1 iron) [import / export as well]
  - [x] Mover (2 copper + 2 iron [1 iron + 1 circuit])
  - [x] Repair Arm (? titanium + ? circuit)
  - [x] Copper Miner
  - [x] Iron Miner
  - [x] Titanium Miner
  - [x] Hydrogen Miner
  - [x] Oxygen Miner
  - [x] ~~Chemical Plant~~
- [x] Ship repair stages
- [x] Play test
- [ ] File size
  - [x] small tilemap instead of tilemap image
  - [x] stricter terser settings
  - [x] ~~inline base64 images~~ (increases size by 2KB)
  - [x] rollup-kontra-plugin (saves about 591B)
  - [x] new roadroller version
